apiVersion: azure.m.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: azure-dns
  namespace: apps-lab
spec:
  credentials:
    secretRef:
      key: creds
      name: azure-secret
      namespace: apps-lab
    source: Secret