apiVersion: azure.m.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: azure-dns
  namespace: crossplane-system
spec:
  credentials:
    secretRef:
      key: creds
      name: azure-crossplane-secret
      namespace: crossplane-system
    source: Secret